### Numpy Tutorial
- it's a python library mainly used for vector type executions (all at once).
- it's used for working with arrays.
- it's short for Numerical Python.

In [1]:
# importing the numpy module
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr)) # see the type carefullt here

[1 2 3 4 5]
<class 'numpy.ndarray'>


#### So whats Numpy excactly in more details
- It also has functions for working in domain of linear algebra, fourier transform, lots of workability with pandas for data manipulation mostly in datapases and matrices.
- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

#### Why even consider using numpy instead of normal list or tuple or anything like that?
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
- Arrays are quite frequently used in data science , where we speed and resources are very important

#### Some more insights into numpy

- Numpy arrays are stored at one `continuous place in memory` unlike lists
- this behavior is called locality of reference computer science.
- Also it's also optimized to work significantly faster with the latest CPU architectures.

In [2]:
# if you do not have the numpy instaled in your system, go to command prompt
# and type pip install numpy and hit enter, this should install the numpy package into your path (where the python files are located)

In [3]:
# to check which versio of python you are using you can check like this
print(np.__version__) # at the time of writing this, the version was 2.2.0

2.2.0


In [4]:
# we can use both list or tuple to create a numpy array like this
arr_tup = np.array((1,2,3,4,5))
arr_lis = np.array([1,2,3,4,5])

print(arr_tup, arr_lis) 
# see both the outputs are excactly the same 
# however when you look closer into the output you'll notice that
# the elements withtin the array aren't seperated by anything like ','.

[1 2 3 4 5] [1 2 3 4 5]


#### Dimensions in Arrays
-  a dimension in arrrays is one level of array depth(nested arrays)
- `nested arrays` means that they have arrays as their elements

In [5]:
# This is a 0-D array
arr = np.array(34)
print(arr) # no bracketts, nothing just one element

34


In [6]:
# Time for 1-D array
arr = np.array([1,2,3,4,5]) 
# for now we have passed a list inside the np.array argument,
# we also could have used a tuple instead of a list
print(arr) # see the values are inside first degree []

[1 2 3 4 5]


In [7]:
# Time for 2-D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr) 
# see this thing because now we have nested arrays within the main array as values
# the degree becomes two and you can clearly see the [[]] - here double

[[1 2 3]
 [4 5 6]]


In [8]:
# 3-D arrays are quite similar in ideology, difference is that 
# we will have multiple nested arrays as elements within nested arrays 
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr) # lookout for the [[[],[]],[[],[]]]

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


- if you wanted to check the dimensions if any array here is how you'd do it
  `use the ndim`

In [10]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim) # 0 degree
print(b.ndim) # 1 degree
print(c.ndim) # 2 degree
print(d.ndim) # 3 degree

0
1
2
3


### Higher Dimensional Arrays
- An array can have any number of dimensions.
- When the array is created, you can define the number of dimensions by using the ndmin
argument

In [12]:
array = np.array([1,2,3,4,5], ndmin = 5)
print(array)
print(f'the number of dimensions are: {array.ndim}') 
# see the [[[[[]]]]] enclosing

[[[[[1 2 3 4 5]]]]]
the number of dimensions are: 5


In [13]:
# we can access numpy array elements just like how we would access 
# any element form a normal list 
arr = np.array([1,2,3,4])
print(arr[0]) # Boo-yaa, you will get the first element as your output

1


In [14]:
# We can even perform some basic arithmetic operations with the elements in and array
aray = np.array((2,1,3,5,4,6))
print(aray[3] * aray[0]) # see we got 10

10


 Accessing elements form any `more than one dimensional` arrays can be a bit challenging

 - Now, to access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.
 - We need to think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [16]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# the first 0 is for selecting the first nested array between the 2 nested within the main array and 1 for the 2nd item in that array
print('2nd element on 1st row: ', arr[0, 1])

# lets try another example
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])


2nd element on 1st row:  2
5th element on 2nd row:  10


In [17]:
# Similarly with the 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# as you may have already guessed, the 0 
# for the 1st among 2 of the multi nested array, 
# and then 1 for the 2nd one in the 1st group
# and finally 2 means the 3rd item of that selected array
print(arr[0, 1, 2])

6


In [18]:
# interestingly numpy does support, negative indexing like this 
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# outputs the last item of the 2nd array inside the nested array
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


#### Numpy Array Slicing
`Some General Things to Keep in Mind`
- Slicing in python means taking elements from one given index to another given index.
- We pass slice instead of index like this: [start:end].
- We can also define the step, like this: [start:end:step].
- If we don't pass start its considered 0
- If we don't pass end its considered length of array in that dimension
- If we don't pass step its considered 1

In [21]:
# Lets do our First Example
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5]) # returns elements from 2 to 5
print(arr[3:]) # returns elements from 3 till the end
print(arr[:4]) # returns elements from the beginning till the fourth item

[2 3 4 5]
[4 5 6 7]
[1 2 3 4]


In [23]:
# Lets have a look at the negative slicing 
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# starting from the 3rd last item all the way to the beginning
print(arr[-3::-1]) # this time we have used the Step attribute as well, 

[5 4 3 2 1]


# Splitting Multi-Dimensional Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# Takes the 2nd array from the original nested array and then does the slicing on that
print(arr[1, 1:4])

In [28]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# This will take both nested array and will output the 3rd item from both of them in the form of a new array
print(arr[0:2, 2])

[3 8]


In [26]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# This takes both the arrays from this nested array and then
# puts the 2nd to 4th item in both the arrays within a new 2-d array
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


#### Let's Talk a bit about data types in Numpy
NumPy has some extra data types,
and refer to data types with one character,
like i for integers, u for unsigned integers etc.

Below is a list of all the data types in Numpy
- `i` - integer
- `b` - boolean
- `u` - unsigned integer
- `f` - float
- `c` - complex float
- `m` - timedelta
- `M` - datatime
- `O` - object
- `S` - string
- `U` - unicode string
- `V` - fixed chunk of memory for other type ( void )



In [32]:
# To check the datatype of the elements present in the array,
# this is something we can do

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr1 = np.array(['apple', 'banana', 'cherry'])
print(arr1.dtype)

int64
<U6


In [33]:
# we could also create arrays with defined data type
arr = np.array([1,2,3,4],dtype = 'S')
print(arr)
print(arr.dtype) 
# we get a weird output after string conversion as there
# - b'1' instead of '1' keep that in mind 

[b'1' b'2' b'3' b'4']
|S1


In [34]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype) # returns int32  

[1 2 3 4]
int32


In [35]:
try:
    arr = np.array(['a', '2', '3'], dtype='i')
    print(arr)
    print(arr.dtype)
except:
    print('Opposi PooPsi')
# the elements present within the numpy array aren't of the same type,
# thats why it threw an error

Opposi PooPsi


#### Converting Data Type on Existing Arrays

- The best way to change the data type of an existing array, is to make a copy of the array with the `astype()` method.

- The astype() function creates a copy of the array, and allows you to `specify the data type` as a parameter.

- The data type can be specified using a `string`, like 'f' for `float`, 'i' for `integer` etc. or you can use the data type directly like float for float and int for integer.

In [36]:
arr = np.array([1.1, 2.1, 3.1]) # this ones a float

newarr = arr.astype('i') # changes it to integer from float

print(newarr)
print(newarr.dtype) #int32

[1 2 3]
int32


In [37]:
# This example is for boolean meaning that,
# if the value is 0 then False otherwise True
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


### Numpy Array Copy vs View
##### The Difference between Copy and View

- The main difference between a copy and a view of an array is that the `copy is a new array`, and the view is just a `view of the original array`.

- The copy owns the data and any changes made to the `copy will not affect original array`, and any changes made to the original array will not affect the copy.

- The view does not own the data and any changes made to the view will affect the original array, and `any changes made to the original array will affect the view.`

In [3]:
# Copy
import numpy as np
arr = np.array([1,2,3,4,5])
cpy_arr = arr.copy()

arr[3] = 2
print(arr)
print(cpy_arr) # remains un-affected

[1 2 3 2 5]
[1 2 3 4 5]


In [5]:
# as the original array changes the view shall change as well
arr = np.array([1,2,3,4,5])
x = arr.view()

arr[1] = 10
print(arr)
print(x) # now the value has been updated here 

[ 1 10  3  4  5]
[ 1 10  3  4  5]


In [6]:
# How to check if Array Owns its Data ?

arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

# this checks
print(x.base) # this returns None meaning this doesn't own the data
print(y.base)

None
[1 2 3 4 5]


In [8]:
# Lets talk about shapes
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape) #returns the shape in this case we get (2,4) 2 elements each having 4 elements

(2, 4)


- Create an array with 5 dimensions using ndmin
- using a vector with values 1,2,3,4 
- and verify that last dimension has value 4

In [9]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape) 
# try to understand the concept here the last dimenson
# is where the elements of the original array is at core wise,
# the other dimensons are cast onto then

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


##### Numpy Array Reshaping
- Reshaping means changing the `shape` of an array.
- The shape of an array is the number of `elements` in each `dimension`.
- By reshaping we can `add or remove dimensions` or `change number of elements in each dimension`.

In [10]:
# From 1-D to 2-D
array = np.array([1,2,3,4,5,6]) # total of 6 elements
new_arr = array.reshape((2,3)) 
# must make sure that the multiplication of the digits matchs the number of elements of the array you wanted to convert 
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [11]:
# Similarly 1-D array to 3-D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2) 
# same logic here 2*3*2 = 12 elements in total
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


If an array has `15 elements` and you want to reshape it to (3,3)- it wont work as `3*3 == 9` so it won't make sense for the rest of the elements to simply `disappear`

### Returns Copy or View


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base) 
# So the base will revert a reshaped array back to normal

[1 2 3 4 5 6 7 8]


#### Unknown Dimension

- You are allowed to have one "unknown" dimension.
- Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
- Pass -1 as the value, and NumPy will calculate this number for you.

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1) 
# we use the -1 here so that the reshape automatically 
# adjusts everything itself

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
# Flattening array means converting a multidimensional array into a 1D array
arr = np.array([[1,2,3],[4,5,6]])
new_arr = arr.reshape(-1) 
print(new_arr)

[1 2 3 4 5 6]


### Iterating Over Numpy Arrays


In [15]:
arr = np.array([[1,2,3],[4,5,6]])
for _ in arr:
    print(_) # this returns the nested arrays

[1 2 3]
[4 5 6]


In [18]:
# now what if we wanted to get all the items within the nested arrays
array = np.array([[[1,2,3],[3,2,1]],[[4,5,6],[6,5,4]],[[7,8,9],[9,8,7]]])
for x in array:
    for y in x:
        for z in y:
            print(z, end = ' ')

# Liked it, I knew you would

1 2 3 3 2 1 4 5 6 6 5 4 7 8 9 9 8 7 

In [19]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr): 
  print(x)

# this is basically the shortcut of the previous one

1
2
3
4
5
6
7
8
